### ISSUE TITLE
My Project doesn`t link when i use libpnet on windows 10

### ISSUE THREAD

**Issue by AvasDream** [libpnet/libpnet#332]
Hello,

 i am trying to integrate libpnet in my rust project but i am not able to compile the project after I add libpnet to cargo.toml and import the pnet crate. Is this an issue with my setup?Is libpnet just for *NIX systems? 

I replicated the problem on my other windows 10 Laptop (Windows 10 Pro, 10.0.17134 Build 17134).
The continous integration Server i am using (travis-ci.org)  had no problems to compile the project, and i assume they have linux at their backend. 

Below you can see my `cargo run` output.

Every help is appreciated :) 

````
    Blocking waiting for file lock on the registry index
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Blocking waiting for file lock on libc-0.2.42.crate
   Compiling libc v0.2.42
   Compiling num_cpus v1.8.0
   Compiling pnet_sys v0.21.0
   Compiling memchr v2.0.1
   Compiling syntex_errors v0.42.0
   Compiling threadpool v1.7.1
   Compiling aho-corasick v0.6.4
   Compiling pnet_datalink v0.21.0
   Compiling regex v0.2.11
   Compiling syntex_syntax v0.42.0
   Compiling syntex v0.42.2
   Compiling pnet_macros v0.21.0
   Compiling pnet_packet v0.21.0
   Compiling pnet_transport v0.21.0
   Compiling pnet v0.21.0
   Compiling projekt v0.1.0 (file:///C:/Users/Tyrell%20Wellick/git/rust-projekt)
warning: unused import: `Sender`
 --> src\main.rs:6:31
  |
6 | use std::sync::mpsc::{channel,Sender}; //channel
  |                               ^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: unused import: `channel`
 --> src\tcp_scans.rs:3:23
  |
3 | use std::sync::mpsc::{channel,Sender}; //channel
  |                       ^^^^^^^

warning: unused imports: `IpAddr`, `Ipv4Addr`
 --> src\icmp_scan.rs:3:16
  |
3 | use std::net::{IpAddr, Ipv4Addr};
  |                ^^^^^^  ^^^^^^^^

warning: unused import: `pnet::transport::TransportChannelType::Layer4`
 --> src\icmp_scan.rs:5:5
  |
5 | use pnet::transport::TransportChannelType::Layer4;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `pnet::transport::TransportProtocol::Ipv4`
 --> src\icmp_scan.rs:6:5
  |
6 | use pnet::transport::TransportProtocol::Ipv4;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `pnet::transport::transport_channel`
 --> src\icmp_scan.rs:7:5
  |
7 | use pnet::transport::transport_channel;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `pnet::packet::ip::IpNextHeaderProtocols`
 --> src\icmp_scan.rs:8:5
  |
8 | use pnet::packet::ip::IpNextHeaderProtocols;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `pnet::packet::Packet`
 --> src\icmp_scan.rs:9:5
  |
9 | use pnet::packet::Packet;
  |     ^^^^^^^^^^^^^^^^^^^^

warning: unreachable pattern
  --> src\main.rs:68:13
   |
68 |             ScanType::Udp => {
   |             ^^^^^^^^^^^^^
   |
   = note: #[warn(unreachable_patterns)] on by default

warning: unused variable: `stream`
  --> src\tcp_scans.rs:12:19
   |
12 |         if let Ok(stream) = TcpStream::connect(addr) {
   |                   ^^^^^^
   |
   = note: #[warn(unused_variables)] on by default
   = note: to avoid this warning, consider using `_stream` instead

warning: unused variable: `ip`
  --> src\icmp_scan.rs:12:18
   |
12 | pub fn ping_scan(ip: String) /*-> bool */ {
   |                  ^^
   |
   = note: to avoid this warning, consider using `_ip` instead

warning: function is never used: `str_to_usize`
  --> src\utility.rs:54:1
   |
54 | pub fn str_to_usize(string: String) -> Option<usize> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(dead_code)] on by default

warning: function is never used: `ping_scan`
  --> src\icmp_scan.rs:12:1
   |
12 | pub fn ping_scan(ip: String) /*-> bool */ {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: linking with `link.exe` failed: exit code: 1181
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\Tyrell Wellick\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.16u6js6g0l3k1ic6.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.17erb31xn70viq4b.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1aq179hixix234ed.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1c3v6slaqysiin5d.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1dqvxks6k2bzkxe.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1e698527iprj2v8f.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1fxq14vrn4hmbyv6.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1h6l2wlif8ioxhqg.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1i1rw0r1vs9bhmdr.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1im38lueib99jsk0.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1jnlhyxj59jycbjv.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1mvmz58owquyropc.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1o6b1la7g4jnv39b.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1q8ffos2d96smbjs.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1rnt618l5epcaf5a.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1s3socv0drccut20.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1um484vjuu3ha50h.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1vut2eft6nlujjxr.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1y16o1qfye96o7m0.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1zeawhkbeobww1zn.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.1zwd8n7bcl3vhvvh.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.236iz806sghm3wx.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.23b3awyhccr072h.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.23tqyymcb18u96mb.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.2jqywn86b2gsqohu.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.2kjrmm4fe2aha78f.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.2lyh15q6cjwzy18c.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.2w6xsa2hbi53xhak.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.3171x0bwu82dptu7.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.3960u8pvbgt79fko.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.3ayaeypdcro9d6yk.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.3cx7oljifvb206q7.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.3fifcd631xjr0zx1.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.3g94tobrpgum5dk6.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.3i5rga4vs82n6cyj.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.3ik0x0hz6l66cx38.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.3kfx4ynvkmi2y9i5.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.3ldk0i2zxftngav8.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.3o7h30h5bxeddjaw.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.3oqznv5oym7l3m4e.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.3rngp6bm2u2q5z0y.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.3ysg602ly0el3m63.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.436dotimmrgzkwfa.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.43v6g0y2xsxoggnt.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.45nf4z58qqykpcpi.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.45pc7c65foh9i35f.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.47dqcamjlp23ma80.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.47kb80rpg37n2ote.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.48721dc4k5qxei0u.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.49a7n47po4ttqjl7.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.49lx1q7cxvpykyv0.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.49qmpuk8w1opmi5q.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.4b8ptp1vn215jmoe.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.4bro8i2eu9dn8hoh.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.4brwxiorhmgsb6oc.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.4bwka44cn8t3u4h3.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.4ezmh1vbs95c5ack.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.4g47d2sx6m33abop.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.4jdnq7xfjeka1bt.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.4sw9hz7i7fiueihz.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.4uabefc56mlk4yon.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.4xq48u46a1pwiqn7.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.4xuhwz5yy6q4gvgg.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.4yh8x2b62dcih00t.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.4ypvbwho0bu5tnww.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.5205e1onhko1v9bb.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.54zq6xwdlu4umqga.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.5544xgl7axh7p8nz.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.55ezy8i7h0n87k30.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.56dly8q07ws8ucdq.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.572bgozz9kcwe4zq.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.57k06xfugllsc526.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.5b1vh7iwaxrgdt9b.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.5beqqbexwb143v6a.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.5gf6du7k58s78kob.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.7p53qlves2rwxx0.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.8xzrsc1ux72v29j.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.98g0d9x8aw3akpe.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.9elsx31vb4it187.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.c6lbtaiefvx3wya.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.e19kx9t7xhzajfl.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.kt25z0521ngsjub.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.mb501chi8fnqgmm.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.n847vnkjamrby94.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.pqmjx25qpxkduz7.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.r5omkko2zyx5xap.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.sd3ak9f4uaqbrdw.rcgu.o" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.sjcqfz2ncn1dupz.rcgu.o" "/OUT:C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.exe" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\projekt-2da329271c8ee4df.crate.allocator.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\Tyrell Wellick\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\Tyrell Wellick\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\Tyrell Wellick\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps" "/LIBPATH:C:\\Users\\Tyrell Wellick\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\pnet-0.21.0/lib" "/LIBPATH:C:\\Users\\Tyrell Wellick\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\libpnet-071ea182ba9f3f17.rlib" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\libthreadpool-0a463ce3e9348fe3.rlib" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\libpnet_datalink-f2bf11e6417576b0.rlib" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\libipnetwork-f22e55d41e51f300.rlib" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\libnum_cpus-2a9dbc56ccc98113.rlib" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\libpnet_transport-94bd5a1030830718.rlib" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\libpnet_packet-e447ccd8143bbfda.rlib" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\libpnet_macros_support-0c7f5a92823f369d.rlib" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\libpnet_base-cf1db3b8691e10da.rlib" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\libpnet_sys-90755697890c7fdf.rlib" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\libws2_32-13c146cb2f1486fa.rlib" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\libwinapi-bbf438b5460ae821.rlib" "C:\\Users\\Tyrell Wellick\\git\\rust-projekt\\target\\debug\\deps\\liblibc-45bfadcb1bbae76f.rlib" "C:\\Users\\Tyrell Wellick\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-e4012f32ed49dbd4.rlib" "C:\\Users\\Tyrell Wellick\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-e06b44655de3deec.rlib" "C:\\Users\\Tyrell Wellick\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-bb7b44a2c820c759.rlib" "C:\\Users\\Tyrell Wellick\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-7a58eced25824fd9.rlib" "C:\\Users\\Tyrell Wellick\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc_system-274f63b9d93efba7.rlib" "C:\\Users\\Tyrell Wellick\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-42d3f88d7348fdd5.rlib" "C:\\Users\\Tyrell Wellick\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_unicode-0d9e538325cba131.rlib" "C:\\Users\\Tyrell Wellick\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-a373617f7ef4ae90.rlib" "C:\\Users\\Tyrell Wellick\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-5d9fbbf902f0a218.rlib" "iphlpapi.lib" "Packet.lib" "ws2_32.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "shell32.lib" "msvcrt.lib"
  = note: Non-UTF-8 output: LINK : fatal error LNK1181: Eingabedatei \"Packet.lib\" kann nicht ge\xf6ffnet werden.\r\n

error: aborting due to previous error

error: Could not compile `projekt`.

To learn more, run the command again with --verbose.

Process finished with exit code 101

```

**Comment by Trolldemorted** [comment]
The linker error message tells you everything you need to know:

```
note: Non-UTF-8 output: LINK : fatal error LNK1181: Eingabedatei \"Packet.lib\" kann nicht ge\xf6ffnet werden.\r\n
```

Your loader must be able to find Packet.dll at startup, and the linker must be able to find Packet.Lib at link time. [The readme tells you where you can get them](https://github.com/libpnet/libpnet#windows). Note that you don't need the nightly (I think?), you can also use Npcap, and you do not neccessarily have to place the .lib into the project folder - putting the .lib into %LIB% and the .dll into %PATH% should be sufficient.

**Comment by AvasDream** [comment]
Oh that is embarassing, not correctly reading the docs and opening an issue. You were totally right after adding the deps everything worked fine. Thank you for your help!

**Comment by mrmonday** [comment]
I've updated the README with your information, thanks @Trolldemorted!

@AvasDream Don't worry about it - please feel free to open more issues for anything you need.

**Comment by fragsalat** [comment]
Hey guys, first of all thx for the project and your work. Unfortunately I am to stupid to setup the dependencies on win10. I've installed winpcap 4.1.3 and copied the Package.lib from the zip archive of the 4.1.2 development pack from WpdPack\Lib\x64\Package.lib to myproject\lib\Package.lib

I'm still having the linker complaining about the not found file

```
error: linking with `link.exe` failed: exit code: 1181
  |
  = note: "G:\\Programme\\Entwicklung\\Visual Studio 2017\\IDE\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.10se9g5kh6ffe431.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.1414uir53ci6z8ga.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.14ub6b67c2s5veif.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.1565k9u4s4ni8qcz.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.17me96tfd8u6zqxh.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.1ayyay0qcaktfmqo.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.1bc2wlp2xaxxp76l.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.1j9g0yktdzhtfqsk.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.1o0gsofwnbcv2tnd.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.1q9c3v71kzclox71.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.1qr1kx7rbwhfdhk.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.1tu6cw9ct3aiguos.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.1xi4ttgdy1otinee.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.1yqetmtofcpmi842.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.205utr4ctcpek32p.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.276rovks32bdicub.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.2agdrl0b9fc08vcn.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.2cz9u2exsml2j1dv.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.2piotdgbscyqj4t7.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.2wk06exbiykdhifp.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.34pc4d1usshlcnwa.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.36f4drrb1zn97wmt.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.39drcbp3qh1h176l.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.39m6hldat6r16fn7.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.3d4crbdqlrz66ao0.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.3dkvjpc2d0fnngwb.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.3ea4vqr5qi8uk5s5.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.3ezaqicmqx6oey69.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.3gu5c8bna1litg9b.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.3lobd02f22s1fbxk.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.3n2ybede6t54h9iw.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.3q7oivkkll026km6.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.3sseef30eqe70cz6.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.3u6a997l7jznv93m.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.3w42542lxzh61qg0.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.3yib9tzudgqb6gze.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.427uj85ui9zf8c3x.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.48bf99qda14ajter.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.4dhpwsmr4y3sekht.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.4g523qtlc9rmrwti.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.4g5d4t6kyf148l3q.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.4h93wvar5badx310.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.4nro35ehk8yip42q.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.4uk4nqxlviq71xt2.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.51fgpp3vgsh26ofi.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.56gvl9xas7stcg5w.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.57uw4kaw5g5sqxip.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.5883hd9ft66g7gk6.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.5asdhjnha550b2vn.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.718l293jim8967b.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.90zrto8it1p5rnz.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.nk66h7f4n5d4py2.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.ozcgfad4h7wf1jw.rcgu.o" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.va01b6keju9ok62.rcgu.o" "/OUT:G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.exe" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\tcp_proxy-a35099f81135531d.b6cmua0qf60l72h.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps" "/LIBPATH:C:\\Users\\tschl\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\pnet-0.23.0/lib" "/LIBPATH:C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libwakey-9fab9474e17cf2b9.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libhex-8a97c93d6043b1ec.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libserde_json-fe9b2ddec5be221d.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libryu-178a8c94b12667f3.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libitoa-c823c2cf343b0f4b.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libpnet-bda6dd18af79613c.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libpnet_transport-736c8911803aa1a2.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libpnet_packet-ac6000826fe2e81e.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libpnet_macros_support-b8ecb9c7d1d64f9a.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libpnet_datalink-03e933b6ec1f5b6b.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libpnet_sys-dc2f850dd619da02.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libws2_32-140730e581a09c7b.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libwinapi-c9e0539c9dc78521.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\liblibc-40dc492a83d0ecc5.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libpnet_base-c9a0a6c3a3998d57.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libipnetwork-f094416d3888400c.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libserde-dfc5fe47092d5784.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libenv_logger-f717f33f74537334.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libtermcolor-ab491947e91cd0d7.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libwincolor-3d0abb4840ddc118.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libwinapi_util-67ad3ff3bef41d71.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libatty-89435fc0a09673d7.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libwinapi-a57bea08d1aed6cd.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libhumantime-d703ac835cf41563.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libquick_error-ff2c15571a0a617a.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libregex-9d46ede5e67b40e7.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libutf8_ranges-6b78c564a7020dbd.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libregex_syntax-02df2f1cfe5f18a3.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libthread_local-38f5edb57c4439cf.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\liblazy_static-fb3bb0bce9a10d6a.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libaho_corasick-3626a2508b321ba9.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libmemchr-037dce02030caf29.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\liblog-6dda55c8f242980c.rlib" "G:\\Data\\projects\\rust\\tcp_proxy\\target\\debug\\deps\\libcfg_if-604b68ddda9d07b2.rlib" "C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-219668e32acece57.rlib" "C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-56e951ee62d0fcf0.rlib" "C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libbacktrace-cfd2e2b8900457a3.rlib" "C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-eb7f6db4a6c6e47b.rlib" "C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-8cc076ae5d2c5ef2.rlib" "C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-a28fc6142231b9af.rlib" "C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-fd674a945e91edbf.rlib" "C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-569eb1a8d0ed4d2d.rlib" "C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-92126d23e5bd5054.rlib" "C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-f9f7fd20de9c727a.rlib" "C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-cb65dbca9de886ca.rlib" "C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-25afbd8e6ef1895f.rlib" "C:\\Users\\tschl\\.rustup\\toolchains\\nightly-2019-08-18-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-912db9a4ae4cbde4.rlib" "iphlpapi.lib" "Packet.lib" "ws2_32.lib" "advapi32.lib" "cfgmgr32.lib" "gdi32.lib" "kernel32.lib" "msimg32.lib" "opengl32.lib" "user32.lib" "winspool.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: Non-UTF-8 output: LINK : fatal error LNK1181: Eingabedatei \"Packet.lib\" kann nicht ge\xf6ffnet werden.\r\n

error: aborting due to previous error
```

**Comment by JuxhinDB** [comment]
Hi @fragsalat -- try dumping the Winpcap libraries into your Rust toolchain, not into your project directory and see if that works.

In your case: `C:\Users\tschl\.rustup\toolchains\nightly-2019-08-18-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib\`

**Comment by fragsalat** [comment]
Thank you, that worked. I guess %LIB% usually would point to that path or? I seem to don't have these variable in my cmd and therefore didn't tried it. 
Hint from rust, debugging isn't possible with MSVC toolchain in clion. Run works.

Thanks <3
